### ISSUE TITLE
implementation of orthographic camera

### ISSUE THREAD

**Issue by max-zilla** [Popov72/TRN2#1]
I have been using your app to capture some images for a TR mapping project I'm working on, love it. However perspective is making some levels tricky. I'm wondering if you can provide any guidance about implementing an ortho camera option in the Babylon Camera/Render/Scene files. I am running a local instance and have some experience with Three JS but limited - I know both engines have some OrthographicCamera support but I don't have a good sense how readily that could be plugged into your existing implementations. Any thoughts that might save time would be appreciated!

**Comment by Popov72** [comment]
For Babylon.js, you can switch to an orthographic camera by changing `PERSPECTIVE_CAMERA` to `ORTHOGRAPHIC_CAMERA` and by setting some values to the orthoLeft/Right/Bottom/Top properties in the `babylonJS/src/SceneParser.ts` file.

So, something like:
```typescript
private createCamera(json: any): void {
    const camera = new UniversalCamera(json.name, new Vector3(...(json.position as Array<number>)), this.tscene.object);

    camera.rotationQuaternion = new Quaternion(...(json.quaternion as []));
    camera.fov = (json.fov * Math.PI) / 180.0;
    camera.minZ = json.near;
    camera.maxZ = json.far;
    camera.mode = BCamera.ORTHOGRAPHIC_CAMERA;
    camera.orthoLeft = X;
    camera.orthoRight = Y;
    camera.orthoBottom = Z;
    camera.orthoTop = W;

    camera.inputs.clear();
    camera.inputs.removeMouse();

    this.scene.setActiveCameraByName(json.name);

    this.tscene.setCamera(new Camera(camera));
}
```
You will have to set some sensible values instead of X/Y/Z/W in the code above (you can start with -100/100/-100/100 and see how it comes).

**Comment by max-zilla** [comment]
@Popov72 thank you kindly, some tweaks to the params and I'm on my way: 
![image](https://user-images.githubusercontent.com/14166971/111916016-09ffc400-8a47-11eb-87bb-18f838df1163.png)
Still playing around with things, the position can still be moved with WASD that moves a "shell" of polys that are drawn and everything outside isn't, which is helpful for some parts like hiding upper floors, but required making the iso image from "bands" captured separately. Either way, exactly what I needed, thanks again for responding.
